### ISSUE TITLE
Incorrect check for Vss pin in rule4_5.py

### ISSUE THREAD

**Issue by hackscribble** [KiCad/kicad-library-utils#104]
Latest KLC rule 4.5.ii treats Vss as a negative power pin which, like ground pins, should be at the bottom of the symbol.  The module `rule4_5.py` treats Vss as a positive power pin.

```
    def checkPowerPins(self):
        PWR = ['^[ad]*v(aa|cc|dd|ss|bat|in)$']
    
        first = True
        
        for pin in self.component.pins:
            name = str(pin['name'].lower())
            for pwr in PWR:
                if re.search(pwr, name, flags=re.IGNORECASE) is not None:
                    # Pin orientation should be "down"
                    if not pin['direction'] == 'D':
                        if first:
                            first = False
                            self.warning("Power pins should be placed at top of symbol")
                        self.warningExtra(pinString(pin))
```

I can work on a PR to move Vss to `checkGroundPins()` if that helps?

**EDIT**

Also, the script does not check for "V+" or "V-" which are mentioned in 4.5.i and 4.5.ii.

**Comment by SchrodingersGat** [comment]
@hackscribble good find, I'll look into this.

`V+` and `V-` are not included in this check because often they are input pins e.g. for differential amps etc. Adding these to this check raises too many false positives.

**Comment by hackscribble** [comment]
I have updated the PR to remove V+ and V-.

**Comment by SchrodingersGat** [comment]
Closed, merged
