### ISSUE TITLE
datasheet-field BLANK no longer checked

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library-utils#105]
The datasheet field of symbols seems to be no longer checked for emptines (KLC 4.9.iv)

Best,
JAN

**Comment by SchrodingersGat** [comment]
Datasheet field is checked in 4.10 and seems to be working fine.

I just tested with `checklib.py ~\kicad\library\*.lib -r 4.10 -s -vv` and it gave a lot of missing datasheet errors.

**Comment by hackscribble** [comment]
4.9 script includes a check for the Datasheet field being invisible but not for emptiness:

```
    def checkDatasheet(self):
        
        # Datasheet field must be invisible
        fail = False
        
        ds = self.component.fields[3]
        
        if self.checkVisibility(ds):
            self.error("Datasheet field must be INVISIBLE")
            fail = True
            
        return fail
```

> Datasheet field is checked in 4.10 and seems to be working fine.

4.10 checks the Description and Keywords fields.  So I thought the "Datasheet" field checked by 4.10 is the "Documentation File Name" in the same dialog box.

![image](https://cloud.githubusercontent.com/assets/7076027/24794853/21473d18-1b7f-11e7-946f-6f04b8e6b824.png)

**Comment by SchrodingersGat** [comment]
Ah you are right @hackscribble - the datasheet field is in the LIB file not the DCM file.

**Comment by SchrodingersGat** [comment]
PR here - https://github.com/KiCad/kicad-library-utils/pull/108
