### ISSUE TITLE
Rule 8.2: incorrect handling of integer pad size

### ISSUE THREAD

**Issue by hackscribble** [KiCad/kicad-library-utils#112]
The function `overpadsBounds()` in `kicad_mod.py` returns incorrect results for many (all?) footprints where one or more of the pads has an integer value for X or Y size.  

Fix is to add `from __future__ import division` to the module.  I will raise a PR.

#### Details

Testing with the SOT-143 footprint from `TO_SOT_Packages_SMD`, pad 2 has the following attributes:

```
Position: -1.1, 0.95
Size: 1, 1.4
Orientation: 270
```
The orientation means that the "X" size relates to the Y direction on the footprint, and vice versa.

The program calculates the coordinates of the pad corners as:

```
-1.800000, 1.950000
-0.400000, 1.950000
-0.400000, 0.950000
-1.800000, 0.950000
```
The Y coordinates are +1 and -0 from the pad centre Y coordinate.  They should be +0.5 and -0.5 from the centre.

```
-1.800000, 1.450000
-0.400000, 1.450000
-0.400000, 0.450000
-1.800000, 0.450000
```

**Comment by SchrodingersGat** [comment]
Thanks @hackscribble , PR is merged
