### ISSUE TITLE
idea for new check

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library-utils#131]
- If there is exactly on FPFilter we should given an error message that the footprint field should be filled
- if FPFilter is empty and footprint field is filled, we should tell the user to give the FPFilter (I think this is already implemeneted)

Just an idea ;-)

JAN

**Comment by SchrodingersGat** [comment]
I like this idea - but perhaps just a warning message rather than error? That way it is to the discretion of the librarian(s) if it makes sense in a particular case.

**Comment by poeschlr** [comment]
@jkriege2 i think this is already implemented?
