### ISSUE TITLE
bash path

### ISSUE THREAD

**Issue by gauravjuvekar** [KiCad/kicad-library-utils#135]
sch/test_sch.sh and pcb/test_kicad_mod.sh have the shebang as `#!/usr/bin/bash"`
Is there a reason for this? The "normal" path on almost all distros is `/bin/bash`

**Comment by diggit** [comment]
Maybe author uses Archlinux or similar distro. Best would be `#!/usr/bin/env bash`, env finds bash anywhere in $PATH.
You can open PR ;)
