### ISSUE TITLE
schlib/autogen holds symbol generators but is in git ignore

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-library-utils#143]
Why is the schlib/autogen folder in gitignore?
It currently holds symbol generator scripts.
Are the scripts in the wrong directory or is the gitignore file wrong?

**Comment by poeschlr** [comment]
@jkriege2 or @SchrodingersGat does either of you know something about this?

**Comment by SchrodingersGat** [comment]
I think this is a mistake. The autogen folder is where the scripts should be, but the *output* of these scripts (the generated files) should be ignored.

**Comment by poeschlr** [comment]
The gitignore file has been updated
