### ISSUE TITLE
Error: Multi-unit symbols with stacked pins and mismatched names

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library-utils#144]
I had a multi-unit symbol with pins that were stacked. I accidentally mis-named the pins so they had different names. When I ran checklib.py I got this:
![image](https://user-images.githubusercontent.com/1936989/29243773-3aee48c4-7f5c-11e7-9201-23ff00cad334.png)

Looking at the rule file I was able to see this was likely because of stacked pins that did not have the same name. And indeed, after aligning the names the error went away.

This check works properly with single-unit symbols in my experience.

**Comment by Ratfink** [comment]
I don't want to bother figuring out exactly when, but this has been fixed.  The script successfully finds stacked pins with different names, and doesn't raise an exception when it happens.
