### ISSUE TITLE
checklib.py isn't specific about metadata errors

### ISSUE THREAD

**Issue by ppelleti** [KiCad/kicad-library-utils#150]
As described in [this pull request](https://github.com/KiCad/kicad-library/pull/1583), `checklib.py -v -c G5LE-1 library/relays.lib` on [this commit](https://github.com/KiCad/kicad-library/tree/0909c07e47340bbfcf2a072912ca34f2fe48dd22) results in:

```
Checking symbol 'G5LE-1':
  Violating Rule 4.10 - Part metadata
    Part meta-data is filled in as appropriate
    Component G5LE-1 has metadata errors:
```

But there is nothing further after the colon.  This is not enough information for me to figure out what the error is.

**Comment by SchrodingersGat** [comment]
Hi @ppelleti the [travis output](https://travis-ci.org/KiCad/kicad-library/builds/270615655?utm_source=github_status&utm_medium=notification) shows that extra information.

To show the extra info, use `-vv` instead of `-v` - this increases the verbosity level of the output.
