### ISSUE TITLE
Centering requirement (S3_1.py) only looks at pin positions

### ISSUE THREAD

**Issue by matthijskooijman** [KiCad/kicad-library-utils#195]
Currently, this check only looks at the pin positions. However, I had so far interpreted this rule so that the symbol *body* should be centered, regardless of the pins. For symmetrical symbols, this does not really matter, but for example in https://github.com/KiCad/kicad-symbols/pull/39 I added assymetrical symbols, that have pins on the right, but not on the left, making the current check confused:

```
checklib.py -p AVR-TPI-6 -v -v Connector_Specialized.lib
Checking symbol 'AVR-TPI-6':
  Violating S3.1
    Origin is be centered on the middle of the symbol
    Symbol not centered on origin
     - Center calculated @ (150, 0)
```

![selection_009](https://user-images.githubusercontent.com/194491/33673608-8b06e6e8-daad-11e7-8202-3e242df5c8b2.png)

In calculating the center, it now completely ignores the left part of the symbol body that is not contained within the pin positions.

I'm not sure what the appropriate fix is, though. Is the policy to center the entire symbol, or just the symbol body in this case?

On a related note, the current check is only correct when the position is exactly centered, but the KLC allows for slightly off-center if truly centering would put the pins off the 100mil grid. AFAICS that means that *if* the pins are on the grid (which has a separate check), then if the center offset is <= 50 mil, it is correct according to this rule (since the symbol can only be moved in 100mil steps, so if the offset would be e.g. 150mil or 75mil, it could be moved one step so the offset becomes 50mil or -25mil respectively, so smaller, but if the offset is <= 50mil, it cannot be lowered further).

**Comment by Ratfink** [comment]
Since the merge of https://github.com/KiCad/kicad-library-utils/pull/197, this bug is at least largely fixed.  If there's a single foreground-filled rectangle in the part, that's used for center calculation; otherwise the pins are used like they were before.
