### ISSUE TITLE
F.Fab and *.SilkS line widths - add warnings?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library-utils#217]
At https://github.com/KiCad/kicad-footprints/pull/280 I realized that there were 0.15mm line widths everywhere but nothing in the Travis output. As it turns out, this is correct.

F.Fab lines are checked if they're within 0.1mm to 0.15mm (inclusive). Silk lines are checked to be either 0.1mm, 0.12mm, or 0.15mm. If the constraints above are met, there is no output from the check script.

KLC (http://kicad-pcb.org/libraries/klc/#_footprint_guidelines) says this is the correct range, but also gives a nominal/recommended value for each line width. There is additional information there detailing why a non-nominal/non-recommended width could be used for silk lines, but nothing for fab lines.

So, should the check scripts generate a warning if a non-nominal/non-recommended line width is used? Not an error, certainly, but just a warning? If so, I can make a PR for that.

BTW, this doesn't apply to the courtyard because there is only one allowed width.

**Comment by Ratfink** [comment]
If it's within the range KLC allows, but not the recommended value, I think a warning might be too stern.  I'd be in favor of an info message myself.
