### ISSUE TITLE
[pcb] throw warning when pad_size/drill size ratio is to small

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad-library-utils#24]
probably it would be a good idea, to throw warnings for possible errors in the footprint. For example, when the Annular ring is to small (which can cause production and solder issues):

http://www.ipc.org/committee/drafts/1-13_d_7251WD1.pdf

**Comment by CarlPoirier** [comment]
Hi Thomas,

That is a great idea!

**Comment by SchrodingersGat** [comment]
@pointhi this has finally been added (to [KLC 2.0](https://github.com/SchrodingersGat/kicad-library/wiki/KLC) which is arriving shortly. Thanks for the idea :)
