### ISSUE TITLE
F9.3: Carve out specific exceptions?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library-utils#246]
https://github.com/KiCad/kicad-footprints/pull/691

For `_ThermalVias` footprints we use the non-via 3D model since the package drawing is the same (and the package doesn't have vias). This often creates a warning that we know is OK.

Should the check script have an exception for this specific case to reduce noise?

**Comment by Ratfink** [comment]
I think a special case for `_ThermalVias` footprints makes sense.  It could not give any warning if the model name is the same as the footprint name without `_ThermalVias`, and give a warning if the model name does contain `_ThermalVias`.

We could do the same for `_HandSolder`, though it would be a bit more involved (we'd also have to find and remove `_Pad*` from the footprint name).  There are also `_CircularHoles` variants for a few footprints, which should have the same treatment.
