### ISSUE TITLE
Coaxial_connectors

### ISSUE THREAD

**Issue by LarryJoy** [KiCad/kicad-library-utils#257]
Change the graphic symbol used for coaxial connectors. In the Connector Library is shown "Conn_Coaxial", "Conn_Coaxial_Power", and "Conn_Coaxial_x2". The graphic symbols shown should be changed to IEC 60617 symbols, which is shown in IEEE Std 315A-1986, Clause 5.6.1A "Coaxial plug and socket".

**Comment by evanshultz** [comment]
The appropriate repo for this topic is https://github.com/KiCad/kicad-symbols, not here.

Including images would make this more salient and help communicate your request.
