### ISSUE TITLE
Library checker has problems with Alias

### ISSUE THREAD

**Issue by greenscreenflicker** [KiCad/kicad-library-utils#27]
The library checker for testing commited files has problems when aliases are defined for the components. (Error 3.8). Please fix.

**Comment by diggit** [comment]
What kind of problem? Any testing input and resulted output?

**Comment by greenscreenflicker** [comment]
Resolved. I realized, that for every alias the text has to be reentered. Then checking works.

**Comment by diggit** [comment]
When you edit documentation for alias, there is button in bottom **Copy Document from Parent**, it does exactly what you want.

**Comment by diggit** [comment]
> that for every alias the text has to be reentered

Than can tell you checklib.py with **-vv** parameter. I really suggest to check your symbols with it before creating PR.
