### ISSUE TITLE
Allow step files in footprints

### ISSUE THREAD

**Issue by drid** [KiCad/kicad-library-utils#275]
According to https://github.com/KiCad/kicad-packages3D both WRL and STEP can be used.

KLC F9.3 should be updated accordingly

**Comment by poeschlr** [comment]
Sorry no we do not allow footprints to point to step files. If kicad needs step it does exchange the file format automatically. We are aware that a better solution would have been to have no file ending at all but we did not have the luxury to start with a clean slate.
