### ISSUE TITLE
Have Travis check for duplicate lines (maybe duplicate pads) 

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/kicad-library-utils#278]
I have seen a few footprints which has multiple lines in the same spots, probably because the were copied and paste and forgot about

**Comment by cp-aquila** [comment]
Can you give an example of a footprint where that applies?

**Comment by Shackmeister** [comment]
For instance this one https://github.com/KiCad/kicad-footprints/pull/1118

Not saying it's a huge problem, but it could be nice to catch them when they come

**Comment by myfreescalewebpage** [comment]
Already seen too and not so easy to catch when making a review!

**Comment by cpresser** [comment]
New patch, that checks different layers.
