### ISSUE TITLE
Schematic line ending test failing

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-library-utils#294]
See https://travis-ci.org/KiCad/kicad-symbols/builds/469174883?utm_source=github_status&utm_medium=notification build for a traceback

**Comment by antoniovazquezblanco** [comment]
Sorry but I will ping @fauxpark and @poeschlr as they participated in the merge of this feature. Thanks!

**Comment by fauxpark** [comment]
Duplicate of #292 - in short, close and reopen the PR to force Travis to use the new .travis.yml.

**Comment by antoniovazquezblanco** [comment]
Thank you very much and sorry for the noise!
