### ISSUE TITLE
pcb check corrupts SMD footprint file.

### ISSUE THREAD

**Issue by crackerizer** [KiCad/kicad-library-utils#3]
Checking SMD footprint with pcb check corrupt the file. I have a copy of the file if you want it.

**Comment by ricardocrudo** [comment]
Yes, please.

**Comment by crackerizer** [comment]
Just sent you the files to you email.

**Comment by ricardocrudo** [comment]
Fixed in the commit ddf5bad08940191e64f6c85e8392fe9da3ba1e46. The problem was the sexpr formatter breaking line when it found a ( inside a string.

**Comment by ricardocrudo** [comment]
Thanks for reporting.
