### ISSUE TITLE
move_part.py does not move alias documentation

### ISSUE THREAD

**Issue by diggit** [KiCad/kicad-library-utils#30]
When moving parts with script `move_part.py` symbol and documentation of main symbol is moved. Unfortunately documentation of all aliases remain in source dcm file.

Once this is fixed, checklib.py should be extended to check unused aliases. There could be a lot of them.

**Comment by diggit** [comment]
@ricardocrudo I noticed, that dcm file write operations are not handled by Schlib class and have to be done manually. What do you think about integration of this functionality into it? This could solve problems (simplify solution) with move_part.py and simplify future use.

**Comment by ricardocrudo** [comment]
Hello @diggit, this issue is duplicated with #4 

I think it is a good idea to integrate them.

**Comment by diggit** [comment]
Dang, 3 opened issues and I create duplicate. I'll take care of this.
