### ISSUE TITLE
New EC for continuous pin numbering

### ISSUE THREAD

**Issue by diggit** [KiCad/kicad-library-utils#36]
In 99% cases, there should be no skipped pin numbers. It is problem for pin count filter in KiCad.
If pin is not used, _Not connected_ pin type + invisibility is solution.

This check is so simple, It could be integrated to existing EC. (EC05 https://github.com/KiCad/kicad-library-utils/pull/29 ?)

If you agree, I'll create PR (new/integrate?).

**Comment by SchrodingersGat** [comment]
I like it. I think Ec05 is a good place for it too. Feel free to make the pr

**Comment by SchrodingersGat** [comment]
I've made this addition to EC05 here: https://github.com/KiCad/kicad-library-utils/pull/29

**Comment by ricardocrudo** [comment]
I'm closing this issue since EC05 is deployed and working. Thanks you both.
