### ISSUE TITLE
checklib.py output isn't necessarily in order

### ISSUE THREAD

**Issue by reportingsjr** [KiCad/kicad-library-utils#53]
This is a very minor bug, but something that I'd like to get fixed at some point.

checklib.py sets up a printer object to print out deleted, added, and updated items. The KLC script sets up a /separate/ printer object to print the KLC violations. Because of this the script output can get jumbled a tiny bit, but nothing that is beyond mildly annoying.

**Comment by SchrodingersGat** [comment]
@reportingsjr closing this as it seems to be working very well for the Travis setup
