### ISSUE TITLE
New Rule: Disallow F.Silks for pads

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad-library-utils#64]
https://github.com/KiCad/kicad-library/issues/774

**Comment by CarlPoirier** [comment]
This is KLC 6.5!

**Comment by pointhi** [comment]
yeah, I mean it would be a good idea adding a check into the ```check_kicad_mod``` script

**Comment by ricardocrudo** [comment]
@CarlPoirier I don't think @pointhi's suggestion is actually covered by KLC 6.5. He is suggesting to not allow to have the F.Silks layer enabled at the Technical Layers. I guess we would need a new rule or an extra check (as we have for symbols). Having it we can extend the checking for the other layers as B.SilkS and maybe ***.User layers.

**Comment by SchrodingersGat** [comment]
Hi @pointhi I have included this in the proposed update to KLC being dicussed here: https://github.com/KiCad/kicad-library/issues/879

Current draft: https://github.com/SchrodingersGat/kicad-library/wiki/KLC

Refer to Rule 9.3

**Comment by SchrodingersGat** [comment]
@pointhi I am closing this as it has been addressed in the upcoming KLC
