### ISSUE TITLE
No silent option in latest library check scripts?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library-utils#93]
I liked that option. May I ask the reason to remove it from both sch and pcb scripts? I can find where it was added around the middle of last year but I don't see any discussion or PRs about why it was removed.

**Comment by SchrodingersGat** [comment]
Can you point to the commit where it was removed? It shouldn't have been

**Comment by evanshultz** [comment]
OK. Good. :) I'm happy it should still be there. I'll check this weekend.

**Comment by evanshultz** [comment]
OK. This is my confusion. I was looking in an old branch. Sorry about that.
