### ISSUE TITLE
Reference in Fabrication layer is missing

### ISSUE THREAD

**Issue by eldarkg** [KiCad/kicad-library-utils#94]
I don't know is it right place for this issue.
Each module should contain reference in fabrication layer:
text field with name '%R'.
This is need for plotting assembly drawings.
This issue applies for all *.pretty repos

**Comment by jkriege2** [comment]
This will be part of the updated KLC: https://github.com/SchrodingersGat/kicad-library/wiki/KLC ... and the scripts can already add it with `--fix`. Some footprints also already have it, most not ... help on this is always welcom!

Best,
JAN

**Comment by SchrodingersGat** [comment]
Please submit a PR for any footprints you spot without the extra RefDes

**Comment by eldarkg** [comment]
@SchrodingersGat Are these FP don't generated with scripts?
For info: 
Pin_Headers.pretty: 845 entries.
TO_SOT_Packages_SMD.pretty: 74 entries.
Housings_DFN_QFN.pretty: 82 entries.
...

Manual add Ref field it is suicide.

**Comment by jkriege2** [comment]
yes many are ... but I think the simples way is to use the `--fix` option of our check-scripts ...

**Comment by jkriege2** [comment]
Also note that several repos are not up to speed with respect to the KLCs in diverse points ... but overhaul is (slowly) in progress!

JAN

**Comment by SchrodingersGat** [comment]
Yes most of those are script generated - see https://github.com/pointhi/kicad-footprint-generator

**Comment by eldarkg** [comment]
@SchrodingersGat Who will be regenerate footprints?
