### ISSUE TITLE
Errors with new scripts

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library-utils#99]
Hi @SchrodingersGat !

Could you please have another look at the new script version and/or Travis-Integration? In some cases it seems to work
https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/41
but here:
https://travis-ci.org/KiCad/kicad-library/builds/218111516
https://travis-ci.org/KiCad/kicad-library/builds/218111557
...
are some strange error messages.

Best,
JAN

**Comment by SchrodingersGat** [comment]
Ok those errors are fixed -> see https://travis-ci.org/KiCad/kicad-library/builds/218283976

However the .pretty scripts are all "failing" in that they report zero errors even if there are errors -> https://travis-ci.org/KiCad/TO_SOT_Packages_SMD.pretty/builds/218111123

I shall sort this one out now.

**Comment by SchrodingersGat** [comment]
Ok, that is fixed too.

**Comment by SchrodingersGat** [comment]
Please double check but I think this is OK to close
